name: keble8263-sdoh-extraction
channels:
  - conda-forge
  - pytorch
  - huggingface
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision 
  - torchaudio
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - ipykernel
  - nltk
  - spacy
  - transformers
  - datasets
  - tokenizers
  - pyyaml
  - tqdm
  - pip
  - pip:
    - sentence-transformers
    - sentencepiece
    - protobuf=3.20.0
    - seqeval
    - plotly
    - wandb
    - tensorboard
    - accelerate
    - python-dotenv
    - click
    - regex